#!/bin/bash
# Automation 3: Daily Brief
# Runs at 08:00 - delivers summary: priorities, Cron health, pending items, AI pulse

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
BRIEF_FILE="$WORKSPACE/memory/daily-${TODAY}.md"
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)

echo "# Daily Brief - $TODAY" > "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "*Generated at $(date '+%H:%M:%S')*" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "---" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

cd "$WORKSPACE"

# 1. Header
echo "## Bon dia, Aleix" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# 2. Priorities for Today
echo "## Prioritats per Avui" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# Check MEMORY.md for projects
if [ -f "$WORKSPACE/MEMORY.md" ]; then
  PRIORITIES=$(grep -A10 "## Current Projects" "$WORKSPACE/MEMORY.md" 2>/dev/null | head -15 || true)
  if [ -n "$PRIORITIES" ]; then
    echo "$PRIORITIES" | while read line; do
      echo "$line" >> "$BRIEF_FILE"
    done
  fi
fi

# Check for todos in memory files
TODOS=$(grep -rE "^\- \[ \]|TODO|FIXME" "$WORKSPACE/memory" 2>/dev/null | head -5 || true)
if [ -n "$TODOS" ]; then
  echo "" >> "$BRIEF_FILE"
  echo "### TASKS pendents:" >> "$BRIEF_FILE"
  echo "$TODOS" | while read t; do
    echo "- $t" | sed 's/.*://' >> "$BRIEF_FILE"
  done
fi
echo "" >> "$BRIEF_FILE"

# 3. Cron Health
echo "## Cron Jobs Health" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "| Job | Status | Last Run |" >> "$BRIEF_FILE"
echo "|-----|--------|----------|" >> "$BRIEF_FILE"

# Check for last night's runs
for job in backup audit daily rolling; do
  LOG_FILE="$WORKSPACE/memory/${YESTERDAY}-${job}.md"
  if [ -f "$LOG_FILE" ]; then
    LAST_RUN=$(grep "Timestamp" "$LOG_FILE" 2>/dev/null | tail -1 | awk '{print $2}' || echo "OK")
    STATUS=$(grep "STATUS" "$LOG_FILE" 2>/dev/null | tail -1 | awk '{print $2}' || echo "OK")
    echo "| $job | $STATUS | $LAST_RUN |" >> "$BRIEF_FILE"
  else
    echo "| $job | No run | - |" >> "$BRIEF_FILE"
  fi
done
echo "" >> "$BRIEF_FILE"

# 4. Pending Items
echo "## Items Pendents" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

PENDING=0

# Check for unresolved TODOs (excluding scripts themselves)
for dir in "$WORKSPACE/navi-os/src"; do
  if [ -d "$dir" ]; then
    TODOS=$(grep -rn "TODO" "$dir" 2>/dev/null | grep -v ".sh:" | head -5 || true)
    if [ -n "$TODOS" ]; then
      echo "### $dir:" >> "$BRIEF_FILE"
      echo "$TODOS" | while read t; do
        echo "- $t" | sed 's/.*TODO: //' >> "$BRIEF_FILE"
      done
      PENDING=$((PENDING + 1))
    fi
  fi
done

[ $PENDING -eq 0 ] && echo "- Cap item pendent" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# 5. AI Pulse / News (placeholder)
echo "## AI Pulse" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "- **OpenClaw**: Active i en desenvolupament" >> "$BRIEF_FILE"
echo "- **Navi OS**: v2.0 en produccio" >> "$BRIEF_FILE"
echo "- **Sector**: Agentes autonomos en creixement" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

# 6. Quick Stats
echo "## Stats" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"
echo "| Metric | Value |" >> "$BRIEF_FILE"
echo "|--------|-------|" >> "$BRIEF_FILE"
echo "| Memory files | $(find $WORKSPACE/memory -name '*.md' 2>/dev/null | wc -l) |" >> "$BRIEF_FILE"
echo "| Scripts | $(find $WORKSPACE/scripts -name '*.sh' 2>/dev/null | wc -l) |" >> "$BRIEF_FILE"
echo "| Cron jobs | 4 |" >> "$BRIEF_FILE"
echo "| Source files | $(find $WORKSPACE/navi-os/src -name '*.jsx' -o -name '*.css' 2>/dev/null | wc -l) |" >> "$BRIEF_FILE"
echo "" >> "$BRIEF_FILE"

echo "---" >> "$BRIEF_FILE"
echo "*Brief generated by Navi OS*" >> "$BRIEF_FILE"

echo "Daily brief created: $BRIEF_FILE"
