#!/bin/bash
# Automation 4: Rolling Documentation
# Runs at midnight - updates docs/SYSTEM-REFERENCE.md

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
SYS_REF="$WORKSPACE/docs/SYSTEM-REFERENCE.md"

mkdir -p "$WORKSPACE/docs"

cat > "$SYS_REF" << 'HEADER'
# System Reference
HEADER

echo "" >> "$SYS_REF"
echo "*Auto-generated at $(date '+%Y-%m-%d %H:%M:%S')*" >> "$SYS_REF"
echo "*DO NOT EDIT MANUALLY - This file is auto-generated by Rolling Docs cron*" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "---" >> "$SYS_REF"
echo "" >> "$SYS_REF"

cd "$WORKSPACE"

# 1. What Changed Today
echo "## What Changed Today ($TODAY)" >> "$SYS_REF"
echo "" >> "$SYS_REF"

# Git changes
if [ -d ".git" ]; then
  TODAY_COMMITS=$(git log --since="00:00" --oneline 2>/dev/null | head -10 || echo "No commits")
  if [ "$TODAY_COMMITS" != "No commits" ]; then
    echo "### Git Commits" >> "$SYS_REF"
    echo '```' >> "$SYS_REF"
    echo "$TODAY_COMMITS" | while read c; do echo "  $c" >> "$SYS_REF"; done
    echo '```' >> "$SYS_REF"
    echo "" >> "$SYS_REF"
  fi
fi

# Modified files
echo "### Files Modified" >> "$SYS_REF"
MODIFIED=$(find . -type f \( -name "*.jsx" -o -name "*.js" -o -name "*.css" -o -name "*.sh" \) -newer /tmp 2>/dev/null | grep -v node_modules | head -15 || true)
[ -z "$MODIFIED" ] && MODIFIED="No files modified today"
echo "$MODIFIED" | while read f; do echo "- $f" >> "$SYS_REF"; done
echo "" >> "$SYS_REF"

# 2. Architecture
echo "## Architecture" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "Navi OS - React + Vite application" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo '```' >> "$SYS_REF"
cat << 'EOF' >> "$SYS_REF"
┌─────────────────────────────────────────────┐
│                   Navi OS                    │
├──────────┬──────────┬───────────┬────────────┤
│   Ops    │  Brain   │    Lab    │   Mission   │
│  (amber) │  (sky)   │  (green)  │   Control   │
└──────────┴──────────┴───────────┴────────────┘
                    │
            ┌───────┴───────┐
            │   OpenClaw    │
            │   (Gateway)   │
            └───────────────┘
EOF
echo '```' >> "$SYS_REF"
echo "" >> "$SYS_REF"

# 3. Module Inventory
echo "## Module Inventory" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "| Module | Purpose | Path |" >> "$SYS_REF"
echo "|--------|---------|------|" >> "$SYS_REF"
echo "| Ops | System operations, Mission Control | navi-os/src/modules/Ops.jsx |" >> "$SYS_REF"
echo "| Brain | Memory, Notes, Daily Briefs | navi-os/src/modules/Brain.jsx |" >> "$SYS_REF"
echo "| Lab | Prototypes, Build Logs | navi-os/src/modules/Lab.jsx |" >> "$SYS_REF"
echo "" >> "$SYS_REF"

# 4. Component Inventory
echo "## Component Inventory" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "| Component | Purpose |" >> "$SYS_REF"
echo "|-----------|---------|" >> "$SYS_REF"
for comp in $(find "$WORKSPACE/navi-os/src/components" -name "*.jsx" 2>/dev/null); do
  NAME=$(basename "$comp" .jsx)
  echo "| $NAME | UI component |" >> "$SYS_REF"
done
echo "" >> "$SYS_REF"

# 5. Active Cron Jobs
echo "## Active Cron Jobs" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "| Job | Schedule | Script |" >> "$SYS_REF"
echo "|-----|----------|--------|" >> "$SYS_REF"
echo "| Repo Backup | Daily 02:00 | 01-repo-backup.sh |" >> "$SYS_REF"
echo "| Overnight Audit | Daily 03:00 | 02-overnight-audit.sh |" >> "$SYS_REF"
echo "| Daily Brief | Daily 08:00 | 03-daily-brief.sh |" >> "$SYS_REF"
echo "| Rolling Docs | Daily 00:00 | 04-rolling-docs.sh |" >> "$SYS_REF"
echo "" >> "$SYS_REF"

# 6. Known Issues
echo "## Known Issues" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo "- None currently documented" >> "$SYS_REF"
echo "" >> "$SYS_REF"

# 7. File Structure
echo "## File Structure" >> "$SYS_REF"
echo "" >> "$SYS_REF"
echo '```' >> "$SYS_REF"
find . -type f \( -name "*.jsx" -o -name "*.js" -o -name "*.css" -o -name "*.sh" -o -name "*.md" \) 2>/dev/null | grep -v node_modules | grep -v ".git" | sort | while read f; do
  echo "$f" >> "$SYS_REF"
done
echo '```' >> "$SYS_REF"
echo "" >> "$SYS_REF"

echo "---" >> "$SYS_REF"
echo "*Documentation updated at $(date)*" >> "$SYS_REF"

echo "System reference updated: $SYS_REF"
