#!/bin/bash
# Automation: Daily AI News Summary
# Runs at 07:00 - fetches AI news with real source links

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
NEWS_FILE="$WORKSPACE/memory/${TODAY}-news.md"

echo "# AI News Summary - $TODAY" > "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "*Generated at $(date '+%H:%M:%S')*" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "---" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

cd "$WORKSPACE"

echo "## Top AI News - $TODAY" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

# Use web search to get real news with sources
get_news() {
  local query="$1"
  local url="$2"
  curl -s --max-time 10 -A "Mozilla/5.0" "$url" 2>/dev/null | grep -oE '(https?://[^"<>]+|title>[^<]+|description>[^<]+)' | head -5 || echo ""
}

# Fetch from multiple sources for real links
fetch_with_links() {
  local search_term="AI artificial intelligence news $(date +%Y-%m-%d)"
  
  # Try Hacker News
  HN_NEWS=$(curl -s --max-time 10 "https://hn.algolia.com/api/v1/search?query=AI&tags=story&hitsPerPage=5" 2>/dev/null || echo "")
  if [ -n "$HN_NEWS" ]; then
    echo "$HN_NEWS" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for i, hit in enumerate(data.get('hits', [])[:5], 1):
        title = hit.get('title', 'No title')
        url = hit.get('url', hit.get('_highlightResult', {}).get('title', {}).get('value', ''))
        if not url or url == title:
            url = f'https://news.ycombinator.com/item?id={hit.get(\"objectID\", \"\")}'
        print(f'{i}. {title}')
        print(f'   Source: {url}')
        print('')
except: pass
" 2>/dev/null || echo "1. AI News unavailable from HN"
  fi
}

echo "### Latest from Hacker News (AI)" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
HN_OUTPUT=$(fetch_with_links)
if [ -n "$HN_OUTPUT" ]; then
  echo "$HN_OUTPUT" | while read line; do echo "$line" >> "$NEWS_FILE"; done
else
  echo "1. No recent AI stories on HN" >> "$NEWS_FILE"
fi
echo "" >> "$NEWS_FILE"

# Alternative: fetch from TechCrunch AI RSS
echo "### TechCrunch AI" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
TC_NEWS=$(curl -s --max-time 10 "https://techcrunch.com/category/artificial-intelligence/feed/" 2>/dev/null | grep -oE '<title>[^<]+</title>|<link>[^<]+</link>' | head -12 | sed 's/<[^>]*>//g' || echo "")
if [ -n "$TC_NEWS" ] && [ "$TC_NEWS" != "TechCrunch AI" ]; then
  echo "$TC_NEWS" | head -10 | tail -8 | nl -w1 -s '. ' | while read line; do 
    echo "$line" | sed 's/http/\n   http/g' >> "$NEWS_FILE"
  done
else
  echo "TechCrunch unavailable, using general AI news" >> "$NEWS_FILE"
fi
echo "" >> "$NEWS_FILE"

# Fallback with real sources if scraping fails
if ! grep -q "http" "$NEWS_FILE"; then
  echo "### Fallback Sources" >> "$NEWS_FILE"
  echo "" >> "$NEWS_FILE"
  echo "1. **Hacker News**: https://news.ycombinator.com (search: AI)" >> "$NEWS_FILE"
  echo "2. **TechCrunch AI**: https://techcrunch.com/category/artificial-intelligence/" >> "$NEWS_FILE"
  echo "3. **The Verge AI**: https://www.theverge.com/ai-artificial-intelligence" >> "$NEWS_FILE"
  echo "4. **ArXiv AI**: https://arxiv.org/list/cs.AI/recent" >> "$NEWS_FILE"
  echo "5. **MIT Tech Review**: https://www.technologyreview.com/topic/artificial-intelligence/" >> "$NEWS_FILE"
  echo "" >> "$NEWS_FILE"
fi

echo "---" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "*Sources: Hacker News, TechCrunch, The Verge, ArXiv*" >> "$NEWS_FILE"
echo "*Generated by Navi OS Daily News Cron*" >> "$NEWS_FILE"

echo "News summary created: $NEWS_FILE"
