#!/bin/bash
# Automation: Daily World News Summary
# Runs at 08:00 - fetches top 10 world news with REAL source links
# IMPORTANT: Never make up news. Always include source URLs and cite sources.

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
WORLD_NEWS_FILE="$WORKSPACE/memory/${TODAY}-world-news.md"

echo "# World News Summary - $TODAY" > "$WORLD_NEWS_FILE"
echo "" >> "$WORLD_NEWS_FILE"
echo "*Generated at $(date '+%H:%M:%S')*" >> "$WORLD_NEWS_FILE"
echo "" >> "$WORLD_NEWS_FILE"
echo "---" >> "$WORLD_NEWS_FILE"
echo "" >> "$WORLD_NEWS_FILE"

cd "$WORKSPACE"

echo "## Top 10 World News - $TODAY" >> "$WORLD_NEWS_FILE"
echo "" >> "$WORLD_NEWS_FILE"

# Fetch all sources and combine into a JSON-like format
python3 << 'PYTHON_SCRIPT' >> "$WORLD_NEWS_FILE"
import subprocess, re, html, json
from datetime import datetime

def fetch_rss(source, url):
    try:
        result = subprocess.run(['curl', '-s', '--max-time', '15', url], capture_output=True, text=True, timeout=20)
        feed = result.stdout
        if not feed:
            return []
        
        item_matches = re.findall(r'<item>(.*?)</item>', feed, re.DOTALL)
        items = []
        
        for item in item_matches[:15]:
            # Title - handle CDATA and HTML entities
            title_match = re.search(r'<title>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</title>', item, re.DOTALL)
            title = title_match.group(1).strip() if title_match else ''
            title = html.unescape(title)
            
            # Link - various formats
            link_match = re.search(r'<link>(https?://[^<]+)</link>', item)
            if not link_match:
                link_match = re.search(r'<guid[^>]*>(https?://[^<]+)</guid>', item)
            link = link_match.group(1).strip() if link_match else ''
            
            # Description
            desc_match = re.search(r'<description>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</description>', item, re.DOTALL)
            desc = desc_match.group(1).strip() if desc_match else ''
            desc = html.unescape(desc)
            desc = re.sub(r'<[^>]+>', '', desc).strip()
            
            # Date
            date_match = re.search(r'<pubDate>(.*?)</pubDate>', item)
            date_str = date_match.group(1).strip() if date_match else ''
            
            if title and link and link.startswith('http'):
                items.append({'title': title, 'link': link, 'desc': desc[:200], 'date': date_str, 'source': source})
        return items
    except Exception as e:
        return []

# Fetch from all sources
all_items = []
all_items.extend(fetch_rss('BBC News', 'https://feeds.bbci.co.uk/news/world/rss.xml'))
all_items.extend(fetch_rss('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml'))
all_items.extend(fetch_rss('The Guardian', 'https://www.theguardian.com/world/rss'))
all_items.extend(fetch_rss('NYT', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml'))

# Deduplicate by title (first 80 chars)
seen = set()
unique = []
for item in all_items:
    key = item['title'].lower()[:80]
    if key not in seen:
        seen.add(key)
        unique.append(item)

# Sort by date
def parse_date(d):
    try:
        return datetime.strptime(d[:25], '%a, %d %b %Y %H:%M:%S')
    except:
        try:
            return datetime.strptime(d[:19], '%Y-%m-%dT%H:%M:%S')
        except:
            return datetime.min

unique.sort(key=lambda x: parse_date(x.get('date', '')), reverse=True)

# Output top 10
for i, item in enumerate(unique[:10], 1):
    title = item['title'].replace('|', '\\|').replace('\n', ' ')
    link = item['link']
    source = item['source']
    desc = item['desc']
    date = item.get('date', '')[:16]
    
    print(f"{i}. {title}")
    print(f"   {link}")
    if desc:
        print(f"   [{source}] {desc}")
    else:
        print(f"   Fuente: {source}")
    if date:
        print(f"   {date}")
    print('')

# Sources footer
print("---")
print("")
print("*Sources: BBC News (feeds.bbci.co.uk), Al Jazeera (aljazeera.com), The Guardian (theguardian.com), NYT (nytimes.com)*")
print(f"*Generated by Navi OS World News Cron - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
PYTHON_SCRIPT

echo "" >> "$WORLD_NEWS_FILE"
echo "World news summary created: $WORLD_NEWS_FILE"
