#!/bin/bash
# Automation: Daily Iran War News Summary
# Runs at 07:30 - fetches top 5 Iran war news with REAL source links
# IMPORTANT: Never make up news. Always include source URLs and cite sources.

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
IRAN_FILE="$WORKSPACE/memory/${TODAY}-iran-war.md"

echo "# Iran War News - $TODAY" > "$IRAN_FILE"
echo "" >> "$IRAN_FILE"
echo "*Generated at $(date '+%H:%M:%S')*" >> "$IRAN_FILE"
echo "" >> "$IRAN_FILE"
echo "---" >> "$IRAN_FILE"
echo "" >> "$IRAN_FILE"

cd "$WORKSPACE"

echo "## Top 5 Iran War News - $TODAY" >> "$IRAN_FILE"
echo "" >> "$IRAN_FILE"

python3 << 'PYTHON_SCRIPT' >> "$IRAN_FILE"
import subprocess, re, html
from datetime import datetime

IRAN_KEYWORDS = ['iran', 'iranian', 'tehran', 'isfahan', 'persian', 'middle east war', 'us-iran', 'iran war', 'iran attack', 'iran nuclear', 'iran sanctions', 'iran oil', 'hormuz', 'trump iran', 'israel iran', 'iran retaliation', 'iran conflict']

def fetch_rss(source, url, max_items=30):
    try:
        result = subprocess.run(['curl', '-s', '--max-time', '15', url], capture_output=True, text=True, timeout=20)
        feed = result.stdout
        if not feed:
            return []
        
        item_matches = re.findall(r'<item>(.*?)</item>', feed, re.DOTALL)
        items = []
        
        for item in item_matches[:max_items]:
            # Title
            title_match = re.search(r'<title>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</title>', item, re.DOTALL)
            title = title_match.group(1).strip() if title_match else ''
            title = html.unescape(title)
            
            # Link
            link_match = re.search(r'<link>(https?://[^<]+)</link>', item)
            if not link_match:
                link_match = re.search(r'<guid[^>]*>(https?://[^<]+)</guid>', item)
            link = link_match.group(1).strip() if link_match else ''
            
            # Description
            desc_match = re.search(r'<description>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</description>', item, re.DOTALL)
            desc = desc_match.group(1).strip() if desc_match else ''
            desc = html.unescape(desc)
            desc = re.sub(r'<[^>]+>', '', desc).strip()
            
            # Date
            date_match = re.search(r'<pubDate>(.*?)</pubDate>', item)
            date_str = date_match.group(1).strip() if date_match else ''
            
            if title and link and link.startswith('http'):
                items.append({'title': title, 'link': link, 'desc': desc[:250], 'date': date_str, 'source': source})
        return items
    except Exception as e:
        return []

def is_iran_related(title, desc):
    text = (title + ' ' + desc).lower()
    return any(kw in text for kw in IRAN_KEYWORDS)

# Fetch from multiple sources
all_items = []
all_items.extend(fetch_rss('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml'))
all_items.extend(fetch_rss('BBC News', 'https://feeds.bbci.co.uk/news/world/rss.xml'))
all_items.extend(fetch_rss('NYT', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml'))

# Filter for Iran-related content
iran_items = [item for item in all_items if is_iran_related(item['title'], item['desc'])]

# Deduplicate by title
seen = set()
unique = []
for item in iran_items:
    key = item['title'].lower()[:80]
    if key not in seen:
        seen.add(key)
        unique.append(item)

# Sort by date
def parse_date(d):
    try:
        return datetime.strptime(d[:25], '%a, %d %b %Y %H:%M:%S')
    except:
        try:
            return datetime.strptime(d[:19], '%Y-%m-%dT%H:%M:%S')
        except:
            return datetime.min

unique.sort(key=lambda x: parse_date(x.get('date', '')), reverse=True)

# Output top 5
if not unique:
    print("No Iran war news found in today's feeds.")
    print("")
else:
    for i, item in enumerate(unique[:5], 1):
        title = item['title'].replace('|', '\\|').replace('\n', ' ')
        link = item['link']
        source = item['source']
        desc = item['desc']
        date = item.get('date', '')[:16]
        
        print(f"{i}. {title}")
        print(f"   {link}")
        if desc:
            print(f"   [{source}] {desc}")
        else:
            print(f"   Fuente: {source}")
        if date:
            print(f"   {date}")
        print('')

print("---")
print("")
print("*Sources: Al Jazeera (aljazeera.com), BBC News (bbc.co.uk), NYT (nytimes.com)*")
print(f"*Generated by Navi OS Iran War News Cron - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
PYTHON_SCRIPT

echo "" >> "$IRAN_FILE"
echo "Iran war news created: $IRAN_FILE"
