#!/bin/bash
# Automation: Daily AI News Summary
# Runs at 07:00 - fetches AI news with REAL source links from multiple sources
# IMPORTANT: Never make up news. Always include source URLs.

set -e

WORKSPACE="/home/user/.openclaw/workspace"
TODAY=$(date +%Y-%m-%d)
NEWS_FILE="$WORKSPACE/memory/${TODAY}-news.md"

echo "# AI News Summary - $TODAY" > "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "*Generated at $(date '+%H:%M:%S')*" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "---" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

cd "$WORKSPACE"

echo "## Top AI News - $TODAY" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

# ============================================================
# 1. Hacker News via Algolia API
# ============================================================
echo "### Hacker News (AI & ML)" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

HN_NEWS=$(curl -s --max-time 15 "https://hn.algolia.com/api/v1/search?query=AI%20OR%20artificial%20intelligence&tags=story&hitsPerPage=5" 2>/dev/null || echo "")

if [ -n "$HN_NEWS" ]; then
  HN_OUTPUT=$(echo "$HN_NEWS" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    hits = data.get('hits', [])
    if not hits:
        print('No recent AI stories on Hacker News.')
    for i, hit in enumerate(hits[:5], 1):
        title = hit.get('title', 'No title')
        obj_id = hit.get('objectID', '')
        url = f'https://news.ycombinator.com/item?id={obj_id}'
        title = title.replace('|', '\\|')
        print(f'{i}. {title}')
        print(f'   {url}')
        print('')
except Exception as e:
    print(f'Error parsing HN data: {e}')
" 2>/dev/null)
  echo "$HN_OUTPUT" >> "$NEWS_FILE"
else
  echo "Hacker News unavailable." >> "$NEWS_FILE"
fi
echo "" >> "$NEWS_FILE"

# ============================================================
# 2. TechCrunch AI RSS
# ============================================================
echo "### TechCrunch AI" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

TC_FEED=$(curl -s --max-time 15 "https://techcrunch.com/category/artificial-intelligence/feed/" 2>/dev/null || echo "")

if [ -n "$TC_FEED" ]; then
  TC_OUTPUT=$(echo "$TC_FEED" | python3 -c "
import sys, re
try:
    content = sys.stdin.read()
    items = re.findall(r'<item>(.*?)</item>', content, re.DOTALL)
    if not items:
        print('No TechCrunch AI articles found.')
    for i, item in enumerate(items[:5], 1):
        title_match = re.search(r'<title>(.*?)</title>', item)
        link_match = re.search(r'<link>(https?://[^<]+)</link>', item)
        title = title_match.group(1).replace('|', '\\|') if title_match else 'No title'
        link = link_match.group(1).strip() if link_match else '#'
        print(f'{i}. {title}')
        print(f'   {link}')
        print('')
except Exception as e:
    print(f'Error parsing TC feed: {e}')
" 2>/dev/null)
  echo "$TC_OUTPUT" >> "$NEWS_FILE"
else
  echo "TechCrunch unavailable." >> "$NEWS_FILE"
fi
echo "" >> "$NEWS_FILE"

# ============================================================
# 3. The Verge via main RSS (AI section not available)
# ============================================================
echo "### The Verge" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"

TV_FEED=$(curl -s --max-time 15 "https://www.theverge.com/rss/index.xml" 2>/dev/null || echo "")

if [ -n "$TV_FEED" ]; then
  TV_OUTPUT=$(echo "$TV_FEED" | python3 -c "
import sys, re
try:
    content = sys.stdin.read()
    # Atom format uses <entry> instead of <item>
    items = re.findall(r'<entry>(.*?)</entry>', content, re.DOTALL)
    if not items:
        print('No The Verge articles found.')
    for i, item in enumerate(items[:5], 1):
        # Title in CDATA within HTML entity
        title_match = re.search(r'<title type=\"html\"><!\[CDATA\[(.*?)\]\]></title>', item)
        title = title_match.group(1).replace('|', '\\|') if title_match else 'No title'
        # Link is in href attribute
        link_match = re.search(r'<link rel=\"alternate\" type=\"text/html\" href=\"(https?://[^\"]+)\"', item)
        link = link_match.group(1).strip() if link_match else '#'
        print(f'{i}. {title}')
        print(f'   {link}')
        print('')
except Exception as e:
    print(f'Error parsing TV feed: {e}')
" 2>/dev/null)
  echo "$TV_OUTPUT" >> "$NEWS_FILE"
else
  echo "The Verge unavailable." >> "$NEWS_FILE"
fi
echo "" >> "$NEWS_FILE"

# ============================================================
# Footer with sources
# ============================================================
echo "---" >> "$NEWS_FILE"
echo "" >> "$NEWS_FILE"
echo "*News aggregated from real-time feeds. Source URLs provided for each article above.*" >> "$NEWS_FILE"
echo "*Sources: Hacker News (hn.algolia.com), TechCrunch (techcrunch.com), The Verge (theverge.com)*" >> "$NEWS_FILE"
echo "*Generated by Navi OS Daily News Cron - $(date '+%Y-%m-%d %H:%M:%S')*" >> "$NEWS_FILE"

echo "" >> "$NEWS_FILE"
echo "News summary created: $NEWS_FILE"
