#!/bin/bash
# ============================================================================
# Multi-Agent Standup Orchestrator
# Spawns each chief as sub-agent, collects status, compiles transcript
# ============================================================================

set -e

WORKSPACE="/home/user/.openclaw/workspace"
MEETINGS_DIR="$WORKSPACE/team/meetings"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H-%M)
STANDUP_FILE="$MEETINGS_DIR/${DATE}-daily-standup.md"
LOG_FILE="$WORKSPACE/logs/${DATE}-standup.log"

# Ensure directories exist
mkdir -p "$MEETINGS_DIR"
mkdir -p "$WORKSPACE/logs"

echo "========================================"
echo "DAILY STANDUP - $DATE $TIME"
echo "========================================"

# Initialize standup report
cat > "$STANDUP_FILE" << EOF
# Daily Standup - $DATE

**Time:** $TIME
**Participants:** ELOM, WARREN, JEFF, SAM
**Orchestrated by:** Navi

---

## Executive Summary

[TBD - to be filled by Navi after collecting reports]

---

## ELOM (Chief Visionary Officer) 🚀

**Status:** 
[TBD]

**Blockers:** 
[TBD]

**Commitments:**
[TBD]

**Needs from team:**
[TBD]

---

## WARREN (Chief Quality Officer) 📊

**Status:** 
[TBD]

**Blockers:** 
[TBD]

**Commitments:**
[TBD]

**Needs from team:**
[TBD]

---

## JEFF (Chief Operations Officer) ⚡

**Status:** 
[TBD]

**Blockers:** 
[TBD]

**Commitments:**
[TBD]

**Needs from team:**
[TBD]

---

## SAM (Chief AI Officer) 🤖

**Status:** 
[TBD]

**Blockers:** 
[TBD]

**Commitments:**
[TBD]

**Needs from team:**
[TBD]

---

## Cross-Department Issues

[TBD - issues affecting multiple teams]

---

## Decisions Made

[TBD - any decisions from standup]

---

## Action Items

| Action | Owner | Due | Priority |
|--------|-------|-----|----------|
| [Action] | [Chief] | [Date] | [High/Med/Low] |

---

## Next Standup

**Scheduled:** Tomorrow 8:30 AM

---

_Transcript generated by Navi Standup Orchestrator_
EOF

echo "Standup file initialized: $STANDUP_FILE"
echo ""
echo "Collecting reports from chiefs..."
echo ""

# Function to collect report from a chief
collect_chief_report() {
    local chief_id=$1
    local chief_name=$2
    local workspace=$3
    
    echo "  Collecting from $chief_name..."
    
    # Read chief's status from their workspace
    if [ -f "$workspace/MEMORY.md" ]; then
        local last_update=$(grep "Last updated" "$workspace/MEMORY.md" | head -1)
        echo "    Last memory update: $last_update"
    fi
    
    if [ -f "$workspace/BACKLOG.md" ]; then
        local pending=$(grep -c "TODO" "$workspace/BACKLOG.md" 2>/dev/null || echo "0")
        echo "    Pending tasks: $pending"
    fi
    
    # Read PM board for chief's tasks
    if [ -f "$WORKSPACE/data/pm-board.json" ]; then
        local in_progress=$(grep -c "\"assignee\": \"$chief_id\".*\"status\": \"in-progress\"" "$WORKSPACE/data/pm-board.json" 2>/dev/null || echo "0")
        local todo=$(grep -c "\"assignee\": \"$chief_id\".*\"status\": \"todo\"" "$WORKSPACE/data/pm-board.json" 2>/dev/null || echo "0")
        echo "    In progress: $in_progress, Todo: $todo"
    fi
    
    echo "    [Report collection complete for $chief_name]"
}

# Collect from each chief
echo ""
echo "=== CHIEF STATUS ==="
collect_chief_report "elom" "ELOM" "$WORKSPACE/team/elom"
collect_chief_report "warren" "WARREN" "$WORKSPACE/team/warren"
collect_chief_report "jeff" "JEFF" "$WORKSPACE/team/jeff"
collect_chief_report "sam" "SAM" "$WORKSPACE/team/sam"

echo ""
echo "========================================"
echo "STANDUP COLLECTION COMPLETE"
echo "========================================"
echo ""
echo "Reports collected. Full transcript at:"
echo "$STANDUP_FILE"
echo ""
echo "Next steps:"
echo "1. Navi reviews reports and fills Executive Summary"
echo "2. Action items are tracked in PM Board"
echo "3. Standup transcript available for Aleix review"

# Update standup with collection status
cat >> "$STANDUP_FILE" << EOF

---

## Collection Log

- ELOM: ✓ Status collected
- WARREN: ✓ Status collected
- JEFF: ✓ Status collected
- SAM: ✓ Status collected

**Collection completed at:** $(date '+%H:%M:%S')

EOF

echo ""
echo "RESULTAT: STANDUP COMPLETAT"
